Improve endpoint/rule lists and filtering of DNS requests
safing/portmaster pull request #379
Opened 2021-08-19 21:29 UTC by dhaavi

2021-08-20 10:38 UTC, ppacher submitted a review, later dismissed

2021-08-23 12:55 UTC, ppacher requested changes

2021-08-23 12:55 UTC, ppacher commented on firewall/master.go
> +	}
aren't we missing a `return` here?

2021-08-23 12:55 UTC, ppacher commented on profile/config.go
>  `, `"`, "`")
IMHO `ensuing` is not a commonly used word. Maybe we should rephrase that for non-nativ-english speakers.

2021-08-23 14:32 UTC, dhaavi commented on firewall/master.go
> +	}
Very good catch!

2021-08-23 21:30 UTC, merged