Reduce compat false positivies
safing/portmaster pull request #586
Opened 2022-03-30 14:37 UTC by dhaavi

- Increase self-check timeouts and threshold
- Fix secure DNS bypass notification to reflect reality
- Add notify threshold for app related notification
- Fix connection locking in firewall packet handler

2022-03-31 07:33 UTC, ppacher requested changes

2022-03-31 07:33 UTC, ppacher commented on network/connection.go
Performance wise I would not use an anonymous function here in the hot-path but rather use a normal, named function

2022-03-31 08:05 UTC, dhaavi commented
Linter failed with internal error.

2022-03-31 08:39 UTC, ppacher submitted a review, later dismissed

2022-04-12 15:40 UTC, ppacher approved these changes

2022-04-13 09:14 UTC, merged